# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000
    
spring:
    # 指定静态资源的路径
    #resources: 
        #static-locations: classpath:/statics/,classpath:/pages/
    # 数据源配置
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/spring-boot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: root
            password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    freemarker:  
        allowRequestOverride: false
        allowSessionOverride: false
        cache: true
        checkTemplateLocation: true
        contentType: text/html
        exposeRequestAttributes: false
        exposeSessionAttributes: false
        exposeSpringMacroHelpers: false
        suffix: .html
        templateEncoding: UTF-8
        templateLoaderPath: classpath:/pages/  #表示所有的模板文件都放在该目录下
        spring.freemarker.settings: 
            locale: zh_CN
            date_format: yyyy-MM-dd
            time_format: HH:mm:ss
            datetime_format: yyyy-MM-dd HH:mm:ss

# Mybatis配置
mybatis:
    mapperLocations: classpath:mappers/**/*.xml
    configLocation: classpath:mybatis.xml
    
    